log_dir: "Checkpoint"
mixed_precision: "fp16"
data_folder: "wikipedia-50"
batch_size: 4
save_interval: 5000
log_interval: 100
num_process: 1 # number of GPUs
num_steps: 1000000

dataset_params:
    tokenizer: "GoToCompany/llama3-8b-cpt-sahabatai-v1-instruct"
    token_separator: " " # token used for phoneme separator (space)
    token_mask: "<mask>" # token used for phoneme mask
    token_pad: "<pad>" # token used for padding
    word_separator: 220 # token used for word separator (<formula>)
    token_maps: "token_maps.pkl" # token map path
    
    max_mel_length: 512 # max phoneme length disamakan dengan max_position_embeddings
    
    word_mask_prob: 0.15 # probability to mask the entire word
    phoneme_mask_prob: 0.8 # probability to mask each phoneme
    replace_prob: 0.5 # probablity to replace phonemes
    
model_params:
    vocab_size: 181
    embedding_size: 512
    hidden_size: 512
    num_attention_heads: 8
    intermediate_size: 2048
    max_position_embeddings: 512
    num_hidden_layers: 6
    dropout: 0.1
